# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ChoroMap
                                 A QGIS plugin
 choropleth map maker
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-04-19
        git sha              : $Format:%H$
        copyright            : (C) 2021 by Cole DiLorenzo
        email                : dilorenzo.20@osu.edu
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

# Initialize Qt resources from file resources.py
from .resources import *
# Our imports
from .Choro_Map_dialog import ChoroMapDialog
import os.path

from PyQt5.QtWidgets import QFileDialog, QToolBar
from os import listdir, getcwd
from qgis.core import (QgsVectorLayer, QgsGraduatedSymbolRenderer, QgsRendererRange, QgsProject, QgsSymbol)
from PyQt5.QtGui import QColor 

class ChoroMap:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'ChoroMap_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&ChoroMap')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

        #get working dir
        self.work_path = getcwd()

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('ChoroMap', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/Choro_Map/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Choropleth Map Maker'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&ChoroMap'),
                action)
            self.iface.removeToolBarIcon(action)

    def choose_folder(self):
        work_path1 = QFileDialog.getExistingDirectory(self.dlg, "Choose data folder")
        if work_path1:
            self.work_path = work_path1
            self.dlg.lineEdit.setText(self.work_path)
            files = listdir(self.work_path)
            shpfiles = []
            for f in files:
                if f[-4:] == '.shp':
                    shpfiles.append(f)
            self.dlg.comboBox.clear()
            self.dlg.comboBox.addItems(shpfiles)
            self.dlg.comboBox.currentTextChanged.connect(self.comboBoxChanged)
    
    def comboBoxChanged(self,val):
        
        filename = self.work_path + '/' + self.dlg.comboBox.currentText()
        msg = 'The input shapefile will be {}'.format(filename)
        self.iface.messageBar().pushInfo('Open', msg)
        
        new_layername = filename.rsplit('/',1)[1]
        self.layer = QgsVectorLayer(filename, new_layername[:-4], 'ogr')
        #QgsProject.instance().addMapLayers([layer])


        field_names = [field.name() for field in self.layer.fields()]
        self.dlg.comboBox_2.clear()
        self.dlg.comboBox_2.addItems(field_names)

    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = ChoroMapDialog()
            
            # clear the line edit widget and set the pushbutton callback
            self.dlg.lineEdit.clear()
            self.dlg.pushButton.clicked.connect(self.choose_folder)

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed

        #not used anymore
        #i was doing the catagories manual before
        """
        def interval_divide2(min, max, intervals):
           assert intervals != 0
           interval_size = (max - min) / intervals
           result = []
           start = min
           end = min + interval_size
           while True:
              result.append([int(start), int(end)])
              start = end + 1
              end = end + interval_size
              if len(result) == intervals:
                 break
           return result
        """        

        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            layer = self.layer
            QgsProject.instance().addMapLayers([layer])
            vals = []
            fld = self.dlg.comboBox_2.currentText()
            for f in layer.getFeatures():
                vals.append(f[fld])
            colors = ['#f1eef6','#d0d1e6','#a6bddb','#74a9cf','#2b8cbe','#045a8d']
            colors = ['#f1eef6','#bdc9e1','#74a9cf','#2b8cbe','#045a8d']
            min = sorted(vals)[0]
            max = sorted(vals)[-1]
            step = (max-min)/len(colors)
            rangeL = []
            for color in colors:
                cat = [min, min+step, color]
                symbol = QgsSymbol.defaultSymbol(layer.geometryType())
                symbol.setColor(QColor(cat[2]))
                qRange = QgsRendererRange(cat[0], cat[1], symbol, '{0:.1f}-{1:.1f}'.format(cat[0], cat[1]))
                rangeL.append(qRange)
                min = (min + step) + 0.1
            renderer = QgsGraduatedSymbolRenderer(fld, rangeL)
            layer.setRenderer(renderer)
            layer.triggerRepaint()
